version: '3'

services:
  app:
    build: .
    ports:
      - "5000:10000"
    environment:
      - DEBUG=true
      - SECRET_KEY=dev-key-for-testing-only
    volumes:
      - ./models_cache:/app/models_cache 