services:
  - type: web
    name: sentiment-analysis-dashboard
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: SOCKETIO_ASYNC_MODE
        value: eventlet
    healthCheckPath: / 