services:
  - type: web
    name: sentiment-analysis-dashboard
    env: python
    buildCommand: pip install tokenizers==0.12.1 && pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: SOCKETIO_ASYNC_MODE
        value: threading
    healthCheckPath: / 